TWEAK_FLOAT(DustyJumpPower, 21.0f, "Force with which the bunny jumps.")
TWEAK_FLOAT(DustyJumpPowerXScale, 0.8f, "Scale applied to the horizontal axis of jump velocity.")
TWEAK_FLOAT(DustyJumpPowerYScaleWhenDown, 0.8f, "Scale applied to the vertical axis of jump velocity, when jumping down.")
TWEAK_FLOAT(DustyJumpPowerScaleAfter2Combo, 1.1f, "Scale applied to jump velocity after two clean jumps in a row.")
TWEAK_FLOAT(DustyJumpPowerScaleAfter3Combo, 1.25f, "Scale applied to jump velocity after three or more clean jumps in a row.")
TWEAK_INT(DustyGraceJumpTime, 20, "Number of 60hz frames after falling in which the bunny can still jump.")
TWEAK_FLOAT(DustyGravity, 0.3f, "Downward gravity force when the bunny is in the air.")
TWEAK_FLOAT(DustyGravityScaleWhenLaunched, 0.75f, "Gravity scale applied when the bunny is launched from a can or stapler.  Persists until the bunny lands.")
TWEAK_FLOAT(DustyAirFriction, 0.98f, "Friction applied continuously to bunny velocity while the bunny is in the air.")
TWEAK_FLOAT(DustyTerminalVelocityDown, 15.0f, "Maximum downward velocity for the bunny." )
TWEAK_FLOAT(DustyAirBoostForSwipe, 1.0f, "Magnitude of force applied to the bunny for reach swipe in mid air.")
TWEAK_FLOAT(DustyAirBoostXForDrag, 1.0f, "Magnitude of horizontal axis force applied to the bunny when dragging in mid air.")
TWEAK_FLOAT(DustyAirBoostYForDrag, 0.5f, "Magnitude of vertical axis force applied to the bunny when dragging in mid air.")
TWEAK_INT(DustyWallStickTime, 0, "Number of 60hz frames to stick to the wall before sliding down.")
TWEAK_INT(DustyWallStickTimeOnIce, 0, "Number of 60hz frames to stick to the wall before sliding down, on ice." )
TWEAK_FLOAT(DustyWallInitialFriction, 0.3f, "Scale applied to vertical velocity when initially sticking to a wall.")
TWEAK_FLOAT(DustyWallInitialFrictionOnIce, 0.75f, "Scale applied to vertical velocity when initially sticking to a wall, on ice." )
TWEAK_FLOAT(DustyWallFriction, 0.95f, "Friction applied continuously to vertical velocity when sliding on a wall.")
TWEAK_FLOAT(DustyWallFrictionOnIce, 0.99f, "Friction applied continuously to vertical velocity when sliding on a wall, on ice.")
TWEAK_FLOAT(DustyWallTerminalVelocityDown, 7.0f, "Maximum downard velocity when sliding on a wall.")
TWEAK_FLOAT(DustyWallTerminalVelocityDownOnIce, 15.0f, "Maximum downard velocity when sliding on a wall, on ice.")
TWEAK_FLOAT(DustyWallGravityScale, 0.5f, "Scale factor applied to gravity when sliding on a wall.")
TWEAK_FLOAT(DustyWallGravityScaleOnIce, 1.0f, "Scale factor applied to gravity when sliding on a wall, on ice." )
TWEAK_FLOAT(DustyHurtTime, 60.0f, "Number of 60hz frames the bunny will remain hurt for after striking a sharp or flaming object.  (Note that landing also clears the hurt state)")
